# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Devel-Profiler
version:      0.02
version_from: lib/POE/Devel/Profiler.pm
installdirs:  site
requires:
    POE:                           0.29

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
